apiVersion: v1
kind: Service
metadata:
  name: nginx-active
spec:
  selector:
    app: nginx
    rollouts-pod-template-hash: active
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80

---
apiVersion: v1
kind: Service
metadata:
  name: nginx-preview
spec:
  selector:
    app: nginx
    rollouts-pod-template-hash: preview
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
